# Generated by Django 4.1.4 on 2022-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
