# Generated by Django 4.1.4 on 2022-12-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_article_modified_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles"),
        ),
    ]
