# Generated by Django 4.1.4 on 2022-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_article_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
